from __future__ import annotations

from pathlib import Path
from typing import Any

from loguru import logger
from tqdm import tqdm
import typer

from spider_silkome_module.miniprot_window_screen.batch_common import (
    fail_if_any_failed,
    read_tsv,
    run_shell,
    summary_path,
    write_tsv,
)

app = typer.Typer(help="Batch run pyGenomeTracks commands generated by build_tracks_batch.")


@app.command()
def main(
    species_manifest: Path = typer.Option(..., "--species-manifest"),
    interim_root: Path = typer.Option(..., "--interim-root"),
    processed_root: Path = typer.Option(..., "--processed-root"),
    force: bool = False,
) -> None:
    del processed_root
    rows = read_tsv(species_manifest)
    summary_rows: list[dict[str, Any]] = []
    logger.info(f"Running pyGenomeTracks for {len(rows)} species")

    for row in tqdm(rows, desc="Run pyGenomeTracks"):
        species = row["species"]
        commands_tsv = Path(row["pygt_commands"])
        try:
            if not commands_tsv.exists():
                summary_rows.append({
                    "species": species,
                    "status": "skipped",
                    "reason": "missing pyGenomeTracks command table",
                    "commands_tsv": str(commands_tsv),
                    "n_commands": 0,
                    "n_run": 0,
                    "n_skipped": 0,
                    "n_plots": 0,
                })
                continue
            command_rows = read_tsv(commands_tsv)
            n_run = 0
            n_skipped = 0
            for command_row in tqdm(command_rows, desc=f"Plot {species}", leave=False):
                output_png = Path(command_row["output_png"])
                if output_png.exists() and not force:
                    n_skipped += 1
                    continue
                output_png.parent.mkdir(parents=True, exist_ok=True)
                run_shell(command_row["command"])
                n_run += 1
            n_plots = len(list((Path(row["interim_dir"]) / "pygenometracks" / "plots").glob("*.png")))
            summary_rows.append({
                "species": species,
                "status": "ok",
                "reason": "",
                "commands_tsv": str(commands_tsv),
                "n_commands": len(command_rows),
                "n_run": n_run,
                "n_skipped": n_skipped,
                "n_plots": n_plots,
            })
        except Exception as exc:
            logger.exception(f"pyGenomeTracks failed for {species}")
            summary_rows.append({
                "species": species,
                "status": "failed",
                "reason": repr(exc),
                "commands_tsv": str(commands_tsv),
                "n_commands": "",
                "n_run": "",
                "n_skipped": "",
                "n_plots": "",
            })

    out = summary_path(interim_root, "pygenometracks")
    write_tsv(out, summary_rows)
    logger.success(f"pyGenomeTracks summary: {out}")
    fail_if_any_failed(summary_rows)


if __name__ == "__main__":
    app()
